### ISSUE TITLE
misc suggestions

### ISSUE THREAD

**Issue by cranmer** [andrzejnovak/CMSStylempl#1]
Nice! I’d suggest adding an example or two in the readme. Maybe even a comparison to an equivalent ROOT based plot.

Might also consider adding this to scikit-hep.

**Comment by andrzejnovak** [comment]
@cranmer This is superseded by https://github.com/andrzejnovak/cmsstyle The idea is for this to be styling only package to go to with what gets developed from https://gitter.im/HSF/mpl-hep and https://docs.google.com/document/d/1ju3JObrPEyT7QpCx3m1YoVp0gFbLay8ZIxtO0mUCvgo/edit#heading=h.3tw53mc90yd Gonna work on it more next month.
